de = {
    "client_id": "Client ID:",
    "title": "Titel:",
    "details": "Details:",
    "state": "Status:",
    "buttons": "Buttons:",
    "image": "Bild:",
    "edit_title": "Titel bearbeiten",
    "manage_images": "Bilder verwalten",
    "update_rich_presence": "Rich Presence aktualisieren",
    "sync_with_apple_music": "Mit Apple Music synchronisieren",
    "paused": "Pausiert",
    "unknown": "Unbekannt",
    "text_1": "Text_1",
    "link_1": "Link_1",
    "text_2": "Text_2",
    "link_2": "Link_2",
    "image_name": "Name_des_Bildes",
    "error": "Fehler",
    "invalid_client_id": "Ungültige Client ID. Bitte überprüfe sie und versuche es erneut.",
    "could_not_connect_to_discord": "Konnte keine Verbindung mit Discord herstellen. Überprüfe ob Discord ausgeführt ist und versuche es erneut.",
    "invalid_first_link": "Der Link beim ersten Button ist ungültig.",
    "invalid_second_link": "Der Link beim zweiten Button ist ungültig.",
    "could_not_update": "Rich Presence konnte nicht aktualisiert werden. Überprüfe ob alle informationen korrekt angegeben wurden und ob Discord ausgeführt ist.",
    "update_available": "Update verfügbar",
    "would_you_like_to_update": "Eine neue Version ist verfübar. Möchtest du sie herunterladen?",
    "apple_music_only_macos": "Mit Apple Music synchronisieren ist aktuell nur auf macOS verfügbar.",
    "enable_minimized_mode": "Minimierten Modus aktivieren",
    "open_program": "Öffnen",
    "stop_program": "Beenden",
    "minimized_not_linux": "Der minimierte Modus ist aktuell nicht auf Linux verfügbar"
}
