en = {
    "client_id": "Client ID:",
    "title": "Title:",
    "details": "Details:",
    "state": "State:",
    "buttons": "Buttons:",
    "image": "Image:",
    "edit_title": "Edit title",
    "manage_images": "Manage images",
    "update_rich_presence": "Update rich presence",
    "sync_with_apple_music": "Sync. with apple music",
    "paused": "Paused",
    "unknown": "Unknown",
    "text_1": "text_1",
    "link_1": "link_1",
    "text_2": "text_2",
    "link_2": "link_2",
    "image_name": "image_name",
    "error": "Error",
    "invalid_client_id": "Invalid ClientID. Please check and try again.",
    "could_not_connect_to_discord": "Could not connect to Discord. Please check if Discord is running and try again.",
    "invalid_first_link": "The link at the first button is invalid.",
    "invalid_second_link": "The link at the second button is invalid.",
    "could_not_update": "Could not update rich presence. Please check if all information have been entered correctly and try again.",
    "update_available": "Update available",
    "would_you_like_to_update": "A new version is available. Would you like to download it?",
    "apple_music_only_macos": "Sync with Apple Music is currently only available on macOS.",
    "enable_minimized_mode": "Enable minimized mode",
    "open_program": "Open",
    "stop_program": "Exit",
    "minimized_not_linux": "Minimized mode is currently not available on Linux"
}
